pub mod matches_route;
pub mod ranking_route;
pub mod login_route;
pub mod bets_route;
pub mod profile_route;
pub mod register_route;
pub mod admin_route;
pub mod upload_match_route;
pub mod upload_result_route;
