services:
  mysql:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pencaucu_db
    healthcheck:
      test: ["CMD", "bash", "-c", "mysql --user=$$USER_NAME --password=$$MYSQL_ROOT_PASSWORD --execute 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 50s
      retries: 10
  backend:
    build: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pencaucu_db
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - REDIS_HOST=redis
      - EMAIL=obligatorio_bd2@outlook.com
      - EMAIL_PASSWORD=123456789ObligatorioBD2
      - JWT_SECRET=A7F886EAD26C3515C24F3D6BECDE905E363871BBD5B750FA66F3CEDD2A4358E5
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - "80:80"
