services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=db_pwd
      - MYSQL_DATABASE=pencaucu_db
    healthcheck:
      test: ["CMD", "bash", "-c", "mysql --user=$$USER_NAME --password=$$MYSQL_ROOT_PASSWORD --execute 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 50s
      retries: 10
  backend:
    build: ./backend
    environment:
      - DB_USER_NAME=root
      - DB_PASSWORD=db_pwd
      - DB_NAME=pencaucu_db
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pencaucu_db
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
